trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python manage.py test
  displayName: 'Run Tests'

- script: |
    python manage.py collectstatic --noinput
    zip -r RockPaperScissors.zip .
  displayName: 'Package Application'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'RockPaperScissors.zip'
    artifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Free Trial>'
    appName: '<python-calculator-app>'
    package: $(Build.ArtifactStagingDirectory)/RockPaperScissors.zip
